user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "p=171") { return 302 /computer-graphics-theses-2016/; }
            if ($query_string = "p=223") { return 302 /ludum-dare-36/; }
            if ($query_string = "p=363") { return 302 /; }
            if ($query_string = "p=578") { return 302 /ludum-dare-37/; }
            if ($query_string = "p=825") { return 302 /computer-graphics-theses-2017/; }
            if ($query_string = "p=1089") { return 302 /ludum-dare-41-tartu/; }
            if ($query_string = "page_id=165") { return 302 /contact/; }
            if ($query_string = "page_id=627") { return 302 /how-to-join/; }
            if ($query_string = "p=640") { return 302 /global-game-jam-2017/; }
            if ($query_string = "p=975") { return 302 /ludum-dare-40/; }
            if ($query_string = "p=1010") { return 302 /global-game-jam-2018-tartu/; }
            if ($query_string = "page_id=2") { return 302 /projects/; }
            if ($query_string = "page_id=544") { return 302 /ludum-dare/; }
            if ($query_string = "page_id=814") { return 302 /manifesto/; }
            if ($query_string = "page_id=886") { return 302 /schedule-fall-2017/; }
            if ($query_string = "page_id=1034") { return 302 /schedule-spring-2018/; }
            if ($query_string = "p=863") { return 302 /ludum-dare-39/; }
            if ($query_string = "p=365") { return 302 /; }
            if ($query_string = "p=366") { return 302 /unity-game-dev-workshop-tartu-student-days-2016/; }
            if ($query_string = "p=856") { return 302 /apt-vr-jam-2017/; }
            if ($query_string = "page_id=376") { return 302 /team-finder/; }
            if ($query_string = "page_id=601") { return 302 /schedule-spring-2017/; }
            if ($query_string = "page_id=1132") { return 302 /schedule-fall-2018/; }
            if ($query_string = "p=102") { return 302 /ludum-dare-35/; }
            if ($query_string = "p=266") { return 302 /apt-game-generator-ole-rohkem-student-fair-2016/; }
            if ($query_string = "p=734") { return 302 /ludum-dare-38/; }
            if ($query_string = "page_id=290") { return 302 /schedule-fall-2016/; }
        }
    }
}
